"""add agriculturor domain models

Revision ID: 55c6daece6a6
Revises: 1a31ce608336
Create Date: 2026-01-17 12:21:03.563122

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55c6daece6a6'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultor',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('localizacao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultor_cpf'), 'agricultor', ['cpf'], unique=True)
    op.create_table('setor',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tamanho', sa.Float(), nullable=True),
    sa.Column('agricultor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aparelho',
    sa.Column('setor_id', sa.Uuid(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('agricultor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ultima_conexao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controlador',
    sa.Column('aparelho_id', sa.Uuid(), nullable=False),
    sa.Column('total_relays', sa.Integer(), nullable=True),
    sa.Column('info_relays', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('assinatura', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aparelho_id'], ['aparelho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlador_aparelho_id'), 'controlador', ['aparelho_id'], unique=True)
    op.create_table('comando',
    sa.Column('controlador_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_criado', sa.DateTime(), nullable=False),
    sa.Column('timestamp_executado', sa.DateTime(), nullable=True),
    sa.Column('comando', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('param', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['controlador_id'], ['controlador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_table('comando')
    op.drop_index(op.f('ix_controlador_aparelho_id'), table_name='controlador')
    op.drop_table('controlador')
    op.drop_table('aparelho')
    op.drop_table('setor')
    op.drop_index(op.f('ix_agricultor_cpf'), table_name='agricultor')
    op.drop_table('agricultor')
    # ### end Alembic commands ###
